#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codepower?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
#MyBatis配置
mybatis:
  mapper-locations:
  - classpath*:mapper/*Mapper.xml
  type-aliases-package: cn.com.codepower.*.entity
  